spring:
  application:
    name: blogs
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
   root: debug
graceful-response:
  # ???Response????????????
  # ??response-class-full-name??response-style?????
#  response-class-full-name:
  # ????????????false
  print-exception-in-global-advice: true
  # Response?????????0
  response-style: 1
  # ???????????????0
  default-success-code: 200
  # ????????????ok
  default-success-msg: ok
  # ?????????????1
  default-error-code: 500
  # ????????????error
  default-error-msg: error
  # ???????????????default-error-code
  default-validate-error-code: 5001
  # ?????(????, *?**?????)???????controller??????
#  exclude-packages:
#    - com.lizhiadmin.pro.module.*.controller
  # ?????????????detailMessage?????Response?msg?
  # ???false?????
  origin-exception-using-detail-message: true
  exclude-packages:
    - org.springdoc.**
    - /swagger-ui/*
    - springfox.**


#springdoc:
#  api-docs:
#    # ????????
#    enabled: true
#    groups:
#      enabled: true
#
#  swagger-ui:
#    # ????????????? true???????????????????/?????
#    persistAuthorization: true
#    url: /v3/api-docs
#    configUrl:
#    disable-swagger-default-url: false
#    display-request-duration: true
#  override-with-generic-response: true
##  group-configs[0]:


#      #packages-to-scan: com.feiniaojin.gracefulresponse.advice.*,com.feiniaojin.gracefulresponse.defaults.*
springfox:
  documentation:
    swagger:
      v2:
        enabled: true